name: Build Masscan Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make

      - name: Add MSYS2 to PATH
        shell: pwsh
        run: echo "$Env:PATH += ';C:\msys64\mingw64\bin'" >> $GITHUB_ENV

      - name: Clone Masscan
        run: git clone https://github.com/robertdavidgraham/masscan.git

      - name: Build Masscan.exe
        run: |
          cd masscan
          make

      - name: Generate dynamic tag
        id: tag
        run: |
          TAG_NAME=masscan-windows-$(date +'%Y%m%d-%H%M%S')
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          git tag $TAG_NAME
          git push origin $TAG_NAME
          
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v1
        with:
          files: masscan/masscan.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
